# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r:
  - bioc-devel

# Attempt to get past time limit by having separate step for preparing cache.
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test

before_script:
  - R -e 'BiocManager::install(version = "devel", ask=FALSE)'
  - R -e 'BiocManager::valid()'

apt_packages:
  - libudunits2-dev
  - libgdal-dev
