# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - bioc-devel
  - release
  - devel
before_script:
  - R -e 'BiocManager::install(version = "devel", ask=FALSE)'
  - R -e 'BiocManager::valid()'

apt_packages:
  - libudunits2-dev
  - libgdal-dev
