# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r:
  - bioc-devel
  - release
  - devel
before_script:
  - R -e 'BiocManager::install(version = "devel", ask=FALSE)'
  - R -e 'BiocManager::valid()'

apt_packages:
  - libudunits2-dev
  - libgdal-dev

r_packages:
  - dplyr
  - cowplot
  - ggplot2
  - future
  - scales

bioc_packages:
  - scater
  - BiocGenerics
  - SingleCellExperiment
  - SummarizedExperiment
  - S4Vectors

r_github_packages:
  - cole-trapnell-lab/monocle3
