# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
r:
  - bioc-devel

# Attempt to get past time limit by having separate step for preparing cache.
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test

r_binary_packages: 
  - stringr
  - dplyr
  - igraph
  - RCurl
  - XML
  - git2r
  - plotly
  - BH
  - tidyr
  - plyr
  - stringi
  - HDF5Array
  - Rcpp
  - reticulate
  - RcppParallel
  - digest
  - jsonlite
  - yaml
  - data.table
  - Rhdf5lib
  - later
  - units

before_script:
  - R -e 'BiocManager::install(version = "devel", ask=FALSE)'
  - R -e 'BiocManager::valid()'

apt_packages:
  - libudunits2-dev
  - libgdal-dev
