# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
sudo: required
r:
  - bioc-release

warnings_are_errors: false

# Attempt to get past time limit by having separate step for preparing cache.
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test

r_binary_packages: 
  - stringr
  - dplyr
  - igraph
  - RCurl
  - XML
  - git2r
  - plotly
  - BH
  - tidyr
  - stringi
  - Rcpp
  - reticulate
  - RcppParallel
  - digest
  - jsonlite
  - yaml
  - data.table
  - later
  - units
  - sf
  - RANN
  - RSQLite
  - ape
  - pscl
  - RhpcBLASctl
  - matrixStats
  - deldir
  - FNN

before_script:
  - R -e 'BiocManager::install(ask=FALSE)'
  - R -e 'BiocManager::valid()'

apt_packages:
  - libudunits2-dev
  - libgdal-dev
